parameters:
    my_article_manager.class:  ProgrammingMoris\HomeBundle\Managers\ArticleManager

services:
    article_manager:
        class:        "%my_article_manager.class%"
        arguments:    ["@doctrine.orm.entity_manager"]
