parameters:
#    programming_moris_home.example.class: ProgrammingMoris\HomeBundle\Example

services:
#    programming_moris_home.example:
#        class: %programming_moris_home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
