parameters:
#    programming_moris_article.example.class: ProgrammingMoris\ArticleBundle\Example

services:
#    programming_moris_article.example:
#        class: %programming_moris_article.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
